export const restaurants = [
    {
        id: 1,
        name: "The Lawns Restaurant",
        cuisine: "International • Steakhouse",
        price: "UGX 120k avg",
        priceLevel: 3,
        location: "Kololo, Kampala",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqxrE4tSERAZkqEFNYEPwdDySczWixUJJDz_AfBiY4iuqg18goOUps2I8mwM3Ey1rzPuQy27YCrGrormTfgUVOY4vRBCkUe30P4Se8rbWTSqUuoWN1EsoKSUbHA5zNeodaR6wg6iTWCQGw4nPEpN4NkrcIOAVerwXklPbgUcz-24eZJlv4qrW2qniuuGvI4L_c-HOwlTe1e_0_Z7aywRp5RwfDcrvlPPbAVA-SWEQrF_2xVd0KYjXu7gGysDrZjXITVUXUbCaSP40",
        featured: true,
        position: [0.3136, 32.5811],
        openNow: true,
        tags: [
            { icon: "event_available", label: "Reservations" },
            { icon: "local_bar", label: "Full Bar" },
        ],
    },
    {
        id: 2,
        name: "Café Javas",
        cuisine: "American • Ugandan • Cafe",
        price: "UGX 35k avg",
        priceLevel: 1,
        location: "Kampala Road",
        rating: 4.5,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxUXbJW2DwR2TOuByZltUMQBQyeXZyeZ15E6wjtr1jKVjV819eYovjWVSh_0gVb8O6fmRsaczeSCJXbt9BMQI9jM6L_5OZQylZKAz9sdBbWMcXHT_wXcEmva0hjYpOMraheX8bj9fKM4O-j77EHVf5kZbrU-lX2NqnI0NRTTVxjQamym1BIJUoNcdxuEvtO_K5rj3BVg65hDIjApXKDg_23DMGru6buT0j0n1qndEt6WfKrZeDaCjOunuzGcuOsALLxznX72EhEAM",
        featured: false,
        position: [0.3156, 32.5861],
        openNow: true,
        tags: [
            { icon: "wifi", label: "Free WiFi" },
            { icon: "delivery_dining", label: "Delivery" },
        ],
    },
    {
        id: 3,
        name: "Khana Khazana",
        cuisine: "Indian • Vegetarian",
        price: "UGX 65k avg",
        priceLevel: 2,
        location: "Nakasero, Kampala",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA2IxToKYrgbXPAmSV5qNbKm8NuO140fglBqfSVnXZOwsiNHsXGR9hvFvkzAEBK7K83MnyIjHIUXAL1GNp3_wxKD6GUyXxFTbCrUnHrD7Nk3uqixO-T_dMfgsQdTEMoRPgURpS6S4KIv0OZCO9CQT5Xa4ioU2EZYe8ru7M6M8n6-1PgnyflHKOjm2AtE6tzC0gq-pvaCg7jF9awgO-VfWkJL1AsYNrjKZfqFkgtLlaAI7bIQYxN2TztB1GTEFWKVOTDMCFK2sKAssU",
        featured: false,
        position: [0.3301, 32.5706],
        openNow: false,
        tags: [
            { icon: "eco", label: "Veg Options" },
            { icon: "event_available", label: "Table Booking" },
        ],
    },
    {
        id: 4,
        name: "Fang Fang Chinese",
        cuisine: "Chinese • Seafood",
        price: "UGX 55k avg",
        priceLevel: 2,
        location: "Bugolobi, Kampala",
        rating: 4.6,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDRyGUVmiZY5ReI-NrsVuh3G_QL0mcKnBOw9fFxhc3saNf0SjUn21670WF6p6b9DLgoDkuw9Z1-rIorLNqRt5DbXrwgW-hNGrrRMBZ3ZGhxn4rVpSWR1pzWyUMjwFOz3m1xXCrK6sqreLFy90Jvy7LRlxjc8jwp8_ml-fnuXQ4yDVDJBVcV8CyZ6G6vQwoDCNcR2NwITl4BSsf0AUAH4vwYRDZSFnM_gvhu_K1sD7ik8Ae74oXSjuYTzHkwm0v0-zI3AJM9ssOS0kE",
        featured: false,
        position: [0.3189, 32.5930],
        openNow: true,
        tags: [
            { icon: "takeout_dining", label: "Takeaway" },
            { icon: "groups", label: "Group Dining" },
        ],
    },
    {
        id: 5,
        name: "Prunes Restaurant",
        cuisine: "Continental • Brunch",
        price: "UGX 95k avg",
        priceLevel: 3,
        location: "Nakasero Hill, Kampala",
        rating: 4.9,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuALgPRLoG64GrIDX80rFbk6bl7_nBTGlhex5UcNBRxWa2olosEsQyO1T2wi3eA7EE_L3Api5hjYQRvocCVSC9ZCLKW2KDYCafv46OVoCilkZLwwk3J7Jf4Nq6_ufJe-F-f35j0idifGDBeJmxN0n5csB-8pODPo3LiPC8rjxkPynjKPEqoH09LimVZHionlHoZz-BrtdB47aGcvH4A0h6UCw_XK4FLaP8CrxCi97yY5qdTp3aUe076Eh-RwdBEj2RundJaoEQg-YwE",
        featured: true,
        position: [0.3225, 32.5759],
        openNow: true,
        tags: [
            { icon: "verified", label: "Award Winning" },
            { icon: "wine_bar", label: "Wine Selection" },
        ],
        urgentMessage: "Booking recommended",
    },
    {
        id: 6,
        name: "2K Restaurant",
        cuisine: "Ugandan • Local Food",
        price: "UGX 25k avg",
        priceLevel: 1,
        location: "Bakuli, Kampala",
        rating: 4.4,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDe7-DC2BhgqtrBxJuWZJVzE-gn61Qy6WUs4vW62hZmSiXjdkcvt4v5qeJSIQW0OVFij5GOSUSEhILfV4Kv3-fmfgZktmbGjtbz65c147CaIpJq1lH98-1LTAYKiXJ0qcoJhMl3GRtei1newuQqIoIL4cD1SjLiCKs0JRygU2s8_YOUpAD2mwHidu2Ox1Vof71ehDoD69oC4EBxbK-093LGlWE3ePs1_wQid7zgD3v9q5YVmThuL9R9MMyMKYCVPLs3tzdihS36Do8",
        featured: false,
        position: [0.3116, 32.5651],
        openNow: true,
        tags: [
            { icon: "lunch_dining", label: "Luwombo" },
            { icon: "timer", label: "Fast Service" },
        ],
    },
    {
        id: 7,
        name: "Mediterraneo",
        cuisine: "Italian • Fine Dining",
        price: "UGX 150k avg",
        priceLevel: 4,
        location: "Kololo, Kampala",
        rating: 4.8,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCXbNlH9CQbROg3UjrrppCqbj6vRGKJhrPInygAvHvTr2qkMexlR5TGTsqF3ezWFqS0eaW31vispzyLeDErblCIQnGd3ORPnPHnNiI7TZxBIv4akWqnDY36vFb7es-PzrN5XH36fRC8ezEKyexnoz_irpnU7YfEehpVdfFvdaZ0y10cfCZmMZK0nZ253EeZroHb_8OlDCvq8xv-u9AJKmC269RJUX804wzeos8iQJ72XDbjmzZbCuJqD3a_3Yr2ndutbP37LR3QJgs",
        featured: true,
        position: [0.3206, 32.5831],
        openNow: true,
        tags: [
            { icon: "flatware", label: "Fine Dining" },
            { icon: "wine_bar", label: "Italian Wines" },
        ],
    },
    {
        id: 8,
        name: "Pardis Persian",
        cuisine: "Persian • Middle Eastern",
        price: "UGX 75k avg",
        priceLevel: 2,
        location: "Kololo, Kampala",
        rating: 4.6,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDnJeJsAlwvapnjI56k0Uwrz2DUwo-TNAAAlJN0EpVJND94_PB8atxoE4Il6WMG8NXxKudxq-GPgBgXkIey9XZh5_qmJy-1qOQORYhaSY04xzYH1xmKMArQY2MF_51UDoBKghlIJAUQ3npcBGDfvvHlaMSONCVCVaRA-nb6TSiWorI1okJSlEfzV4qrca9Lv95jGabu20dpBgYYdzE0zOUHIkTx7cD_uOO550_O_2TcnzrvgAmOtAxET8iY2LJz7a-ESqHjtMX2ySw",
        featured: false,
        position: [0.3256, 32.5881],
        openNow: true,
        tags: [
            { icon: "kebab_dining", label: "Kebabs" },
            { icon: "outdoor_grill", label: "Garden Seating" },
        ],
    },
    {
        id: 9,
        name: "Yamasen",
        cuisine: "Japanese • Sushi",
        price: "UGX 130k avg",
        priceLevel: 4,
        location: "Muyenga, Kampala",
        rating: 4.7,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQn4he55E_wf1aDICLtbg0gwo-mZMEu0-r7V0l5L71CxlgO5mWYdunW57wyacPWK9waDuWTCbFFTyHWEEap2dQAqH4_06I74h5jzvgI7gRvId_VVnsAqL-LMja3xbdJ71pb6b1p9AftNEIErBJNQ770wiI5rAwcGJzBdyUOYeTSTlhbrC0xYSXOKge-DVJRGVAeb0L5s0aNkDCtZoT80kkKPVKG-4J4-hcMXuJZG7Ov9qw0QIWLzA8HvecMDqE2imcJiy6lfi8aYg",
        featured: true,
        position: [0.2956, 32.6051],
        openNow: true,
        tags: [
            { icon: "set_meal", label: "Sushi Bar" },
            { icon: "deck", label: "Terrace View" },
        ],
    },
    {
        id: 10,
        name: "Mythos Greek",
        cuisine: "Greek • Mediterranean",
        price: "UGX 110k avg",
        priceLevel: 3,
        location: "Kololo, Kampala",
        rating: 4.5,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2Wipfzv_FKEJz6SnrO1cGaMoRL0BC3-aZmxEZm63qv4QbyjinCoOmnzWVGsgIKdHzwiMGwCUFZNqT5h0lPqh3rExFbXa-J8S1xuwzJGu9-PzEf34EixJVi-0jO8j2luuJowpG1mGYwxWjnIRXgKtkZnznEcZO21C0bj5Zj55fAfnW4ePZ38Pwg0cQDYBYF7uUy8NUaT5KIt3qvktbVLIx3aU4Z9AO6vH0Mr8_ETcWoEnAGRw-Z3zyiCloGgbR6Krjru0bEwtrF_Q",
        featured: false,
        position: [0.3286, 32.5851],
        openNow: true,
        tags: [
            { icon: "bakery_dining", label: "Meze" },
            { icon: "groups", label: "Family Style" },
        ],
    },
    {
        id: 11,
        name: "Shaka Zulu",
        cuisine: "Ugandan • Grill",
        price: "UGX 30k avg",
        priceLevel: 1,
        location: "Bugolobi, Kampala",
        rating: 4.3,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA6PSxI4azub0WZrVSxlxXWKN8Si1u15D2uZXNKdpyFFqxdjAHZUjoV5h3spPnri9VmAmXOIf2sfFGrALgnT3DStapTvadHvmW520rHfEpnwgDqsZvCtRj3E06sKUSIA1y3UoKk_iYJHyqgozrVb4PDFmT9gordGSIZ4Lw9aNfMrFYeJgAsScTKYnsWz29GqU8W-KhPnHUSkogBNtwFbuHCmZFG9aafIjzGf-MOYhJ6_lD9PG4v5AvGaOthppgAcQ1OxUvYrglQdLY",
        featured: false,
        position: [0.3166, 32.6031],
        openNow: true,
        tags: [
            { icon: "outdoor_grill", label: "BBQ" },
            { icon: "sports_bar", label: "Sports Bar" },
        ],
    },
    {
        id: 12,
        name: "Great Wall Ntinda",
        cuisine: "Chinese • Traditional",
        price: "UGX 45k avg",
        priceLevel: 2,
        location: "Ntinda, Kampala",
        rating: 4.2,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBL82-g4mLSKp_g_YJSs8ieuWFubbYg4eEp3l1cJ6OhGDanrhlAS5yzvYzkVP1BJ4CDR_wOkgzsCYHteRPLjFnt_GjLrDr5jKSxQHd1V0JZPgrWGeuqUH75vvcn5n4e832qif6LL8_f1SyeQt8djAMHgxWJ4V1lNUQuqSy62cSuORy8gM7FAmepa2Ad3-94Y1aWxnZttLmSnsIJbvfrLwy5MajCLghaHN07MhtTxeqbMdFMo3x_lziqxYIBNuLOdKrA3esI2AX0HiU",
        featured: false,
        position: [0.3556, 32.6131],
        openNow: true,
        tags: [
            { icon: "takeout_dining", label: "Fast Takeaway" },
            { icon: "ramen_dining", label: "Noodles" },
        ],
    },
];
